[package]
name = "architect-docs"
version.workspace = true
edition.workspace = true

[dependencies]
architect-tools = { workspace = true }
async-trait = { workspace = true }
ignore = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
similar = { workspace = true }
tokio = { workspace = true, features = ["fs"] }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { version = "1", features = ["full"] }
